### ISSUE TITLE
The test accuracy of this article makes 76%. What is the accuracy of the best CNN + LSTM, ucf101 dataset

### ISSUE THREAD

**Issue by MachineLearning11** [Keiku/Action-Recognition-CNN-LSTM#1]
The accuracy of trian is 100%, but the accuracy of test is 76%. Is there a problem，hope can answer my questions ，thank

**Comment by Keiku** [comment]
This repository is a version that fixes bugs in the original repository, so I think it behaves the same as the original repository. I didn't understand the training log issue. For example, what is the status of the training log of other UCF101 Action Recognition tasks?

**Comment by Keiku** [comment]
@MachineLearning11 

First of all, the results 91.27% of the original repository are not reproduced. I have confirmed this. It behaves according to this issues https://github.com/eriklindernoren/Action-Recognition/issues/12. This seems to be confirmed by you too.

The CNN-LSTM benchmark does not seem to be officially reported. At least not listed in Papers With Code.

UCF101 Benchmark (Action Recognition) | Papers With Code https://paperswithcode.com/sota/action-recognition-in-videos-on-ucf101

I believe that split 1 has a test accuracy of around 76%, but I don't know what the truth is. Since the breakthrough of I3D, it has become mainstream to use pretraining of large datasets, and it seems that no one is interested in classic methods like CNN-LSTM. The closest thing to CNN-LSTM may be the classic 3d-resnet method. I think that is also the result of about 70% to 80%. The following is detailed about I3D.

Quo Vadis, Action Recognition? A New Model and the Kinetics Dataset | Papers With Code https://paperswithcode.com/paper/quo-vadis-action-recognition-a-new-model-and

**Comment by MachineLearning11** [comment]
> @机器学习11
> 
> 首先，原库91.27%的结果没有复现。我已经证实了这一点。它的行为根据这个问题[eriklindernoren/Action-Recognition#12](https://github.com/eriklindernoren/Action-Recognition/issues/12)。这似乎也得到了你的证实。
> 
> CNN-LSTM 基准似乎没有官方报道。至少没有在 Papers With Code 中列出。
> 
> UCF101 基准（动作识别）| 带代码的论文https://paperswithcode.com/sota/action-recognition-in-videos-on-ucf101
> 
> 我相信 split 1 的测试准确率在 76% 左右，但我不知道真相是什么。自从I3D突破以来，使用大数据集的预训练已经成为主流，似乎没有人对CNN-LSTM这样的经典方法感兴趣。最接近 CNN-LSTM 的可能是经典的 3d-resnet 方法。我认为这也是大约 70% 到 80% 的结果。下面详细介绍I3D。
> 
> Quo Vadis，动作识别？新模型和动力学数据集 | 带代码的论文https://paperswithcode.com/paper/quo-vadis-action-recognition-a-new-model-and

Thank you very much for your reply. I still have some questions to answer,
I mainly test the driver's behavior

First question: can these motion recognition be monitored in real time with cameras? 
Second, is there an algorithm suitable for the mobile terminal? I think CNN + LSTM is better because it has less data. I find that the speed of I3D is also relatively fast,

**Comment by Keiku** [comment]
@MachineLearning11

> First question: can these motion recognition be monitored in real time with cameras?

I roughly searched for paper, but it seems possible.

[1906.07052] Towards Real-Time Action Recognition on Mobile Devices Using Deep Models https://arxiv.org/abs/1906.07052

> Second, is there an algorithm suitable for the mobile terminal? I think CNN + LSTM is better because it has less data. I find that the speed of I3D is also relatively fast,

I also think CNN + LSTM is better. For real-time purposes, you may want to use a lightweight backbone or model pruning.
